/**
 * Tool Schemas Registry
 * AUTO-GENERATED by @winstain/toolkit-cli — DO NOT EDIT BY HAND.
 */
import { createSchemas } from "@winstain/toolkit/core";

import { authLoginSchema } from "./auth/login/schema";
import { authLogoutSchema } from "./auth/logout/schema";
import { authRefreshSchema } from "./auth/refresh/schema";
import { authVerifySchema } from "./auth/verify/schema";
import { userRetrieveSchema } from "./user/retrieve/schema";
import { userUpdateSchema } from "./user/update/schema";

export const schemas = createSchemas(
  authLoginSchema,
  authLogoutSchema,
  authRefreshSchema,
  authVerifySchema,
  userRetrieveSchema,
  userUpdateSchema
);

export type ToolSchemas = typeof schemas;
export type ToolMethod = keyof ToolSchemas & string;
