/**
 * Tools Registry
 * AUTO-GENERATED by @winstain/toolkit-cli — DO NOT EDIT BY HAND.
 */
import { authLogin } from "./auth/login/tool";
import { authLogout } from "./auth/logout/tool";
import { authRefresh } from "./auth/refresh/tool";
import { authVerify } from "./auth/verify/tool";
import { userRetrieve } from "./user/retrieve/tool";
import { userUpdate } from "./user/update/tool";
import { toolkit } from "./server";

export const tools = toolkit.createTools(
  authLogin,
  authLogout,
  authRefresh,
  authVerify,
  userRetrieve,
  userUpdate
);

export type Tools = typeof tools;
export type ToolKey = keyof Tools & string;
